---
- hosts: consul
  roles:
    - consul

- hosts: docker-hosts
  roles:
    - docker-host

- hosts: docker-registries
  roles:
    - docker-registry

- hosts: jenkins-servers
  roles:
    - common
    - git-client
    - docker-host
    - mariadb
    - jenkins-server
    - github-client
    - {role: rvm, rvm_user: 'jenkins' }

