---
- name: Install kernel update (12.04)
  apt: pkg={{item}} state=installed
  with_items:
    - linux-image-generic-lts-raring
    - linux-headers-generic-lts-raring
  register: add_packages
  sudo: yes

- name: Reboot
  shell: sleep 2s && reboot &
  changed_when: false
  sudo: yes
  when: add_packages|changed

- name: Wait for the server to come up
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=30 state=present
  when: add_packages|changed
