---
- name: Install prerequisite packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - curl
    - bison
    - build-essential
    - zlib1g-dev
    - libssl-dev
    - libxml2-dev
    - libreadline6-dev
    - git-core
  sudo: yes

- name: Install nodejs (needed by some Rails projects)
  apt: pkg=nodejs state=present update_cache=yes cache_valid_time=3600
  sudo: yes

